//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.18 at 11:45:01 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://iban.mano.lt/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lt.mano.iban.schemas;
